DOMAIN = "openkairo"
PANEL_NAME = "openkairo_builder"
PANEL_TITLE = "OpenKAIRO OS"
PANEL_ICON = "mdi:view-dashboard-edit"
PANEL_URL = "openkairo"
GITHUB_API_URL = "https://api.github.com/repos/open-kairo/smart-kairo"
BRIGHT_SKY_URL = "https://api.brightsky.dev/weather"
CONF_POSTCODE = "postcode"
